[package]
name = "miner-rust"
version = "0.2.0"
authors = ["rllola <rllola80@gmail.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.10.10", features = ["blocking","json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.2"
hmac-sha256 = "0.1.6"
rust-scrypt = "1.3.0"
toml = "0.5.8"
