[package]
name = "miner-rust"
version = "0.2.2"
authors = ["rllola <rllola80@gmail.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.11", features = ["blocking","json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
hmac-sha256 = "1.1.6"
rust-scrypt = "1.3"
toml = "0.7.2"
koibumi-base58 = "0.0.1"