name: Build binary

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Binary
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: dogecoin-miner-rust-linux-amd64
          - os: macos-latest
            asset_name: dogecoin-miner-rust-macos-amd64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --locked
    - name: Create Archive
      run: tar -czf ${{ matrix.asset_name }}.tar.gz ./target/release/miner-rust
