name: Build and create release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create Release
    
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    name: Build Artefacts
    needs: release
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: dogeocin-miner-rust-linux-amd64
          - os: macos-latest
            asset_name: dogeocin-miner-rust-macos-amd64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v2
    - name: Run Tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --locked
    - name: Create Archive
      run: tar -czf ${{ matrix.asset_name }}.tar.gz ./target/release/miner-rust

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./${{ matrix.asset_name }}.tar.gz
        asset_name: ${{ matrix.asset_name }}.tar.gz
        asset_content_type: application/gzip 
