name: Build Binaries

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: dogecoin-miner-rust-linux-amd64
          - os: macos-latest
            asset_name: dogecoin-miner-rust-macos-amd64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --locked
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}-${{ github.ref_name }}.zip
        path: ./target/release/miner-rust
        retention-days: 1

  release:
    name: Create Draft Release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Needed so `gh release create` works
      - uses: actions/download-artifact@v5
      - run: ls -lh
      - name: Create draft
        run: gh release create ${{github.ref_name}} dogecoin-miner-rust-linux-amd64-${{github.ref_name}}.zip dogecoin-miner-rust-macos-amd64-${{github.ref_name}}.zip -d --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}