name: Rust tests

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v2
    - name: Windows extra for rust-scrypt
      if: runner.os == 'Windows'
      run: |
        rustup component add rust-src
        for /f %%i in ('rustc --print sysroot') do set RUST_SRC_PATH=%%i\lib\rustlib\src\rust\src
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
